package RoomBooking;


/**
* RoomBooking/RoomBookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomBooking.idl
* Thursday, November 23, 2017 10:59:11 o'clock PM EST
*/

public interface RoomBookingInterface extends RoomBookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RoomBookingInterface
