package RoomBooking;


/**
* RoomBooking/RoomBookingInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomBooking.idl
* Saturday, December 9, 2017 5:17:42 AM EST
*/

public interface RoomBookingInterfaceOperations 
{
  boolean createRoom (String no, String date, String timeslot, String username);
  boolean deleteRoom (String no, String date, String timeslot, String username);
  int bookRoom (String no, String date, String timeslot, String username, String campus, int flag);
  boolean cancelBooking (String bookingID, String username);
  String getAvailableTimeSlot (String date, String username);
  int changeReservation (String bookingID, String username, String campus, String newroomno, String newdate, String newtimeslot);
} // interface RoomBookingInterfaceOperations
