package RoomBooking;


/**
* RoomBooking/RoomBookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomBooking.idl
* Saturday, December 9, 2017 2:00:24 AM EST
*/

public interface RoomBookingInterface extends RoomBookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RoomBookingInterface
