package RoomBooking;


/**
* RoomBooking/RoomBookingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomBooking.idl
* Wednesday, November 22, 2017 6:17:16 o'clock PM EST
*/

public interface RoomBookingInterface extends RoomBookingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RoomBookingInterface
